name: Update Test Data

on:
  workflow_dispatch:
    inputs:
      retry_failures:
        description: 'Retry previously failed files'
        required: false
        default: false
        type: boolean
      force_trigger_tests:
        description: 'Force trigger leiden-js tests (for testing)'
        required: false
        default: false
        type: boolean
  schedule:
    # Check for updates every 6 hours
    - cron: '0 */6 * * *'

jobs:
  update-test-data:
    runs-on: ubuntu-latest
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
    
    steps:
    - name: Cache git repository
      uses: actions/cache@v4
      with:
        path: .git
        key: git-${{ github.sha }}
        restore-keys: |
          git-

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('docker-compose.yml') }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Check for idp.data submodule updates
      id: submodule_check
      run: |
        # Get current submodule commit
        CURRENT_COMMIT=$(cd idp.data && git rev-parse HEAD)
        echo "Current commit: $CURRENT_COMMIT"
        
        # Update submodule to latest
        npm run get-data
        
        # Get new commit after update
        NEW_COMMIT=$(cd idp.data && git rev-parse HEAD)
        echo "New commit: $NEW_COMMIT"
        
        # Check if there are updates
        if [ "$CURRENT_COMMIT" != "$NEW_COMMIT" ]; then
          echo "has_updates=true" >> $GITHUB_OUTPUT
          echo "idp.data updated from $CURRENT_COMMIT to $NEW_COMMIT"
          git add idp.data
        else
          echo "has_updates=false" >> $GITHUB_OUTPUT
          echo "No idp.data updates"
        fi

    - name: Start XSugar container
      if: steps.submodule_check.outputs.has_updates == 'true' || github.event_name == 'workflow_dispatch'
      run: |
        # Build with cache using docker buildx directly
        docker buildx build \
          --cache-from type=local,src=/tmp/.buildx-cache \
          --cache-to type=local,dest=/tmp/.buildx-cache-new,mode=max \
          --tag xsugar \
          https://github.com/papyri/xsugar.git
        
        # Move cache for next run if it exists
        if [ -d "/tmp/.buildx-cache-new" ]; then
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
        fi
        
        # Start the container with compose
        docker compose up --wait xsugar

    - name: Generate edition roundtrips
      if: steps.submodule_check.outputs.has_updates == 'true' || github.event_name == 'workflow_dispatch'
      run: |
        if [ "${{ inputs.retry_failures }}" = "true" ]; then
          npx tsx create-idp-roundtrips.ts edition --retry-failures
        else
          npx tsx create-idp-roundtrips.ts edition
        fi

    - name: Generate translation roundtrips
      if: steps.submodule_check.outputs.has_updates == 'true' || github.event_name == 'workflow_dispatch'
      run: |
        if [ "${{ inputs.retry_failures }}" = "true" ]; then
          npx tsx create-idp-roundtrips.ts translation --retry-failures
        else
          npx tsx create-idp-roundtrips.ts translation
        fi

    - name: Stop XSugar container
      if: steps.submodule_check.outputs.has_updates == 'true' || github.event_name == 'workflow_dispatch'
      run: npm run xsugar:down

    - name: Check for changes
      if: steps.submodule_check.outputs.has_updates == 'true' || github.event_name == 'workflow_dispatch'
      id: changes
      run: |
        git add .
        if git diff --staged --quiet; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "has_test_data_changes=false" >> $GITHUB_OUTPUT
          echo "No changes to commit"
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
          # Check if any actual test data files changed (not just state files)
          if git diff --staged --name-only | grep -E '^roundtrips/' > /dev/null; then
            echo "has_test_data_changes=true" >> $GITHUB_OUTPUT
            echo "Test data files changed"
          else
            echo "has_test_data_changes=false" >> $GITHUB_OUTPUT
            echo "Only non-test-data files changed (state files, submodule)"
          fi
        fi

    - name: Commit and push changes
      if: (steps.submodule_check.outputs.has_updates == 'true' || github.event_name == 'workflow_dispatch') && steps.changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Get submodule commit info for commit message
        cd idp.data
        SUBMODULE_COMMIT=$(git rev-parse HEAD)
        SUBMODULE_SHORT=$(git rev-parse --short HEAD)
        cd ..
        
        git commit -m "Update test data to idp.data@${SUBMODULE_SHORT}

        Updated idp.data submodule to ${SUBMODULE_COMMIT}"
        
        git push

    - name: Trigger leiden-js tests
      if: steps.changes.outputs.has_test_data_changes == 'true' || inputs.force_trigger_tests == true
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.LEIDEN_JS_TRIGGER_TOKEN }}" \
          https://api.github.com/repos/cceh/leiden-js/dispatches \
          -d '{"event_type":"idp-test-data-updated","client_payload":{"commit":"${{ github.sha }}","test_data_commit":"'"$(cd idp.data && git rev-parse HEAD)"'"}}'

    - name: Summary
      run: |
        if [ "${{ steps.submodule_check.outputs.has_updates }}" = "false" ] && [ "${{ github.event_name }}" = "schedule" ]; then
          echo "ℹ️ No idp.data updates available"
        elif [ "${{ steps.changes.outputs.has_test_data_changes }}" = "true" ]; then
          echo "✅ Test data updated successfully and leiden-js notified"
        elif [ "${{ steps.changes.outputs.has_changes }}" = "true" ]; then
          echo "✅ Repository updated (state files only, no test data changes)"
        else
          echo "ℹ️ No changes needed - test data is up to date"
        fi